name: destroy
on:
  workflow_dispatch:
env:
  region: ap-south-1
  bucket: for-tfstate-file
  key1: terraform.tfstate
  table: for-lock-file-2
jobs:
  job1:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

     
     
     
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.region}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}

      - name: Initialize Terraform
        run: |
          cd demo1
          terraform init -backend-config="bucket=$bucket" -backend-config="key=$key1" -backend-config="dynamodb_table=$table"         

      - name: destroy Terraform
        run: |
          cd demo1
          terraform destroy -lock=false -auto-approve 
               
     
