# This is a basic workflow to help you get started with Actions

name: Plan / Test On PR

on:
  push:
    branches:
      - master
env:
  region: ap-south-1
  bucket: for-tfstate-file
  key1: terraform.tfstate
  table: for-lock-file
jobs:
  job1:
    name: terraform
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Run terraform fmt check
        run: terraform fmt 
     
     
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.region}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          cd demo1
          terraform init -backend-config="bucket=$bucket" -backend-config="key=$key1" -backend-config="dynamodb_table=$table"         

      - name: Plan Terraform
        run: |
          cd demo1
          terraform plan         
      - name: Apply Terraform
        run: |
          cd demo1
          terraform apply -auto-approve
               
     
